import React from 'react'

const Header = () => {
    return (
        <div style={{ backgroundImage: `url(headerBackground.jpg)`, 
        backgroundPosition: 'center',
        backgroundRepeat: 'no-repeat',
        backgroundSize: 'cover'}}>

            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>
            <h1>
                Railway 
            </h1>

        </div>
    )
}

export default Header